language: node_js
node_js:
  - '10.15.3'

matrix:
  include:
    - os: osx

    - os: linux

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

cache:
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - npm i -g npm@6.14.4
  - sh ./scripts/fetchNodeBinaries.sh

install:
  - npm install

script:
  - npm run lint-ci
  - npm run build-dll
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_BRANCH" == "master" ]]; then
      npm run package-ci
    fi
