language: node_js
node_js:
  - node

matrix:
  include:
    - os: osx
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  
    - os: linux
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

cache:
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - npm i -g npm@6.9.0
  - sh ./fetchNodeBinaries.sh

install:
  - npm install

script:
  - npm run lint-ci
  - npm run build-dll
  - echo $TRAVIS_OS_NAME
  - |
    if [ $TRAVIS_OS_NAME == "osx" ]; then 
      rm -f release/auth.md
      rm -f release/publishFilesList.txt
      npm run package-all
      sh ./deployDistributables.sh
      sh ./deployAuthMd.sh
    fi
