language: node_js
node_js:
  - '12.13.0'

matrix:
  include:
    - os: osx
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

cache:
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - npm i -g npm@6.12.0
  - sh ./scripts/fetchNodeBinaries.sh

install:
  - npm install

script:
  - npm run lint-ci
  - npm run build-dll
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_BRANCH" == "master" ]]; then
      npm run package-ci
    fi
