// flow-typed signature: 66f9e8d0caaedd733b38330f793e5208
// flow-typed version: <<STUB>>/babel-root-slash-import_v^1.1.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-root-slash-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-root-slash-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-root-slash-import/build/helper' {
  declare module.exports: any;
}

declare module 'babel-root-slash-import/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-root-slash-import/build/helper.js' {
  declare module.exports: $Exports<'babel-root-slash-import/build/helper'>;
}
declare module 'babel-root-slash-import/build/index.js' {
  declare module.exports: $Exports<'babel-root-slash-import/build/index'>;
}
declare module 'babel-root-slash-import/index' {
  declare module.exports: $Exports<'babel-root-slash-import'>;
}
declare module 'babel-root-slash-import/index.js' {
  declare module.exports: $Exports<'babel-root-slash-import'>;
}
