// flow-typed signature: 3fa9c7295ad80a044131059541fd1cd2
// flow-typed version: <<STUB>>/react-native-schemes-manager_v^1.0.5/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-schemes-manager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-schemes-manager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-schemes-manager/src/fix-libraries' {
  declare module.exports: any;
}

declare module 'react-native-schemes-manager/src/fix-script' {
  declare module.exports: any;
}

declare module 'react-native-schemes-manager/src/hide-library-schemes' {
  declare module.exports: any;
}

declare module 'react-native-schemes-manager/src/index' {
  declare module.exports: any;
}

declare module 'react-native-schemes-manager/src/utilities' {
  declare module.exports: any;
}

declare module 'react-native-schemes-manager/src/verify-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-schemes-manager/index' {
  declare module.exports: $Exports<'react-native-schemes-manager'>;
}
declare module 'react-native-schemes-manager/index.js' {
  declare module.exports: $Exports<'react-native-schemes-manager'>;
}
declare module 'react-native-schemes-manager/src/fix-libraries.js' {
  declare module.exports: $Exports<'react-native-schemes-manager/src/fix-libraries'>;
}
declare module 'react-native-schemes-manager/src/fix-script.js' {
  declare module.exports: $Exports<'react-native-schemes-manager/src/fix-script'>;
}
declare module 'react-native-schemes-manager/src/hide-library-schemes.js' {
  declare module.exports: $Exports<'react-native-schemes-manager/src/hide-library-schemes'>;
}
declare module 'react-native-schemes-manager/src/index.js' {
  declare module.exports: $Exports<'react-native-schemes-manager/src/index'>;
}
declare module 'react-native-schemes-manager/src/utilities.js' {
  declare module.exports: $Exports<'react-native-schemes-manager/src/utilities'>;
}
declare module 'react-native-schemes-manager/src/verify-config.js' {
  declare module.exports: $Exports<'react-native-schemes-manager/src/verify-config'>;
}
