[main]
genesis-time = "2020-01-29T08:12:02+00:00"
layer-duration-sec = "300"
layer-average-size = "30"
layers-per-epoch = "6"
genesis-active-size = "50"
poet-server = "poet.unruly.io:50002"
sync-request-timeout = "20000"
hdist = "10"

[p2p]
network-id = "1"

[p2p.swarm]
bootstrap = true
randcon = "8"
bootnodes = ["spacemesh://63iLVGx3WKj96G8XjY4oLtgowgyT1wQKDYTPob3Mhubt@34.73.217.215:7513"]

[api]

[time]

[post]
post-space = "1048576"

[reward]
base-reward = {abs = "50000000000000"}

[hare]
hare-round-duration-sec = "30"
hare-committee-size = "30"
hare-max-adversaries = "14"
hare-exp-leaders = "5"
hare-wakeup-delta = "30"
hare-limit-iterations = "10"

[hare-eligibility]
eligibility-confidence-param = "25"
eligibility-epoch-offset = "0"

[logging]
app = "info"
post = "info"
stateDb= "info"
state = "info"
store = "info"
poetDb = "info"
meshDb = "info"
trtl = "info"
atxDb = "info"
block-eligibility = "info"
mesh = "info"
sync = "info"
block-oracle = "info"
hare-oracle = "info"
hare = "info"
block-builder = "info"
block-listener = "info"
poet = "info"
nipst = "info"
atx-builder = "info"
hare-beacon = "info"
