/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_rpc_status_pb = require('./google/rpc/status_pb.js');
var types_pb = require('./types_pb.js');
goog.exportSymbol('proto.spacemesh.v1.SubmitTransactionRequest', null, global);
goog.exportSymbol('proto.spacemesh.v1.SubmitTransactionResponse', null, global);
goog.exportSymbol('proto.spacemesh.v1.TransactionState', null, global);
goog.exportSymbol('proto.spacemesh.v1.TransactionState.TransactionState', null, global);
goog.exportSymbol('proto.spacemesh.v1.TransactionsIds', null, global);
goog.exportSymbol('proto.spacemesh.v1.TransactionsStateRequest', null, global);
goog.exportSymbol('proto.spacemesh.v1.TransactionsStateResponse', null, global);
goog.exportSymbol('proto.spacemesh.v1.TransactionsStateStreamRequest', null, global);
goog.exportSymbol('proto.spacemesh.v1.TransactionsStateStreamResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.spacemesh.v1.TransactionsIds = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.spacemesh.v1.TransactionsIds.repeatedFields_, null);
};
goog.inherits(proto.spacemesh.v1.TransactionsIds, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.spacemesh.v1.TransactionsIds.displayName = 'proto.spacemesh.v1.TransactionsIds';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.spacemesh.v1.TransactionsIds.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.spacemesh.v1.TransactionsIds.prototype.toObject = function(opt_includeInstance) {
  return proto.spacemesh.v1.TransactionsIds.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.spacemesh.v1.TransactionsIds} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spacemesh.v1.TransactionsIds.toObject = function(includeInstance, msg) {
  var f, obj = {
    transactionIdList: jspb.Message.toObjectList(msg.getTransactionIdList(),
    types_pb.TransactionId.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.spacemesh.v1.TransactionsIds}
 */
proto.spacemesh.v1.TransactionsIds.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.spacemesh.v1.TransactionsIds;
  return proto.spacemesh.v1.TransactionsIds.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.spacemesh.v1.TransactionsIds} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.spacemesh.v1.TransactionsIds}
 */
proto.spacemesh.v1.TransactionsIds.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new types_pb.TransactionId;
      reader.readMessage(value,types_pb.TransactionId.deserializeBinaryFromReader);
      msg.addTransactionId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.spacemesh.v1.TransactionsIds.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.spacemesh.v1.TransactionsIds.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.spacemesh.v1.TransactionsIds} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spacemesh.v1.TransactionsIds.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransactionIdList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      types_pb.TransactionId.serializeBinaryToWriter
    );
  }
};


/**
 * repeated TransactionId transaction_id = 1;
 * @return {!Array<!proto.spacemesh.v1.TransactionId>}
 */
proto.spacemesh.v1.TransactionsIds.prototype.getTransactionIdList = function() {
  return /** @type{!Array<!proto.spacemesh.v1.TransactionId>} */ (
    jspb.Message.getRepeatedWrapperField(this, types_pb.TransactionId, 1));
};


/** @param {!Array<!proto.spacemesh.v1.TransactionId>} value */
proto.spacemesh.v1.TransactionsIds.prototype.setTransactionIdList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.spacemesh.v1.TransactionId=} opt_value
 * @param {number=} opt_index
 * @return {!proto.spacemesh.v1.TransactionId}
 */
proto.spacemesh.v1.TransactionsIds.prototype.addTransactionId = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.spacemesh.v1.TransactionId, opt_index);
};


proto.spacemesh.v1.TransactionsIds.prototype.clearTransactionIdList = function() {
  this.setTransactionIdList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.spacemesh.v1.SubmitTransactionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.spacemesh.v1.SubmitTransactionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.spacemesh.v1.SubmitTransactionRequest.displayName = 'proto.spacemesh.v1.SubmitTransactionRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.spacemesh.v1.SubmitTransactionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.spacemesh.v1.SubmitTransactionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.spacemesh.v1.SubmitTransactionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spacemesh.v1.SubmitTransactionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    transaction: msg.getTransaction_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.spacemesh.v1.SubmitTransactionRequest}
 */
proto.spacemesh.v1.SubmitTransactionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.spacemesh.v1.SubmitTransactionRequest;
  return proto.spacemesh.v1.SubmitTransactionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.spacemesh.v1.SubmitTransactionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.spacemesh.v1.SubmitTransactionRequest}
 */
proto.spacemesh.v1.SubmitTransactionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setTransaction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.spacemesh.v1.SubmitTransactionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.spacemesh.v1.SubmitTransactionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.spacemesh.v1.SubmitTransactionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spacemesh.v1.SubmitTransactionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransaction_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes transaction = 1;
 * @return {!(string|Uint8Array)}
 */
proto.spacemesh.v1.SubmitTransactionRequest.prototype.getTransaction = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes transaction = 1;
 * This is a type-conversion wrapper around `getTransaction()`
 * @return {string}
 */
proto.spacemesh.v1.SubmitTransactionRequest.prototype.getTransaction_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getTransaction()));
};


/**
 * optional bytes transaction = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTransaction()`
 * @return {!Uint8Array}
 */
proto.spacemesh.v1.SubmitTransactionRequest.prototype.getTransaction_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getTransaction()));
};


/** @param {!(string|Uint8Array)} value */
proto.spacemesh.v1.SubmitTransactionRequest.prototype.setTransaction = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.spacemesh.v1.SubmitTransactionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.spacemesh.v1.SubmitTransactionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.spacemesh.v1.SubmitTransactionResponse.displayName = 'proto.spacemesh.v1.SubmitTransactionResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.spacemesh.v1.SubmitTransactionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.spacemesh.v1.SubmitTransactionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.spacemesh.v1.SubmitTransactionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spacemesh.v1.SubmitTransactionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: (f = msg.getStatus()) && google_rpc_status_pb.Status.toObject(includeInstance, f),
    txstate: (f = msg.getTxstate()) && proto.spacemesh.v1.TransactionState.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.spacemesh.v1.SubmitTransactionResponse}
 */
proto.spacemesh.v1.SubmitTransactionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.spacemesh.v1.SubmitTransactionResponse;
  return proto.spacemesh.v1.SubmitTransactionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.spacemesh.v1.SubmitTransactionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.spacemesh.v1.SubmitTransactionResponse}
 */
proto.spacemesh.v1.SubmitTransactionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_rpc_status_pb.Status;
      reader.readMessage(value,google_rpc_status_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 2:
      var value = new proto.spacemesh.v1.TransactionState;
      reader.readMessage(value,proto.spacemesh.v1.TransactionState.deserializeBinaryFromReader);
      msg.setTxstate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.spacemesh.v1.SubmitTransactionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.spacemesh.v1.SubmitTransactionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.spacemesh.v1.SubmitTransactionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spacemesh.v1.SubmitTransactionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_rpc_status_pb.Status.serializeBinaryToWriter
    );
  }
  f = message.getTxstate();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.spacemesh.v1.TransactionState.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.rpc.Status status = 1;
 * @return {?proto.google.rpc.Status}
 */
proto.spacemesh.v1.SubmitTransactionResponse.prototype.getStatus = function() {
  return /** @type{?proto.google.rpc.Status} */ (
    jspb.Message.getWrapperField(this, google_rpc_status_pb.Status, 1));
};


/** @param {?proto.google.rpc.Status|undefined} value */
proto.spacemesh.v1.SubmitTransactionResponse.prototype.setStatus = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.spacemesh.v1.SubmitTransactionResponse.prototype.clearStatus = function() {
  this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.spacemesh.v1.SubmitTransactionResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TransactionState txstate = 2;
 * @return {?proto.spacemesh.v1.TransactionState}
 */
proto.spacemesh.v1.SubmitTransactionResponse.prototype.getTxstate = function() {
  return /** @type{?proto.spacemesh.v1.TransactionState} */ (
    jspb.Message.getWrapperField(this, proto.spacemesh.v1.TransactionState, 2));
};


/** @param {?proto.spacemesh.v1.TransactionState|undefined} value */
proto.spacemesh.v1.SubmitTransactionResponse.prototype.setTxstate = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.spacemesh.v1.SubmitTransactionResponse.prototype.clearTxstate = function() {
  this.setTxstate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.spacemesh.v1.SubmitTransactionResponse.prototype.hasTxstate = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.spacemesh.v1.TransactionsStateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.spacemesh.v1.TransactionsStateRequest.repeatedFields_, null);
};
goog.inherits(proto.spacemesh.v1.TransactionsStateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.spacemesh.v1.TransactionsStateRequest.displayName = 'proto.spacemesh.v1.TransactionsStateRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.spacemesh.v1.TransactionsStateRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.spacemesh.v1.TransactionsStateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.spacemesh.v1.TransactionsStateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.spacemesh.v1.TransactionsStateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spacemesh.v1.TransactionsStateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    transactionIdList: jspb.Message.toObjectList(msg.getTransactionIdList(),
    types_pb.TransactionId.toObject, includeInstance),
    includeTransactions: jspb.Message.getFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.spacemesh.v1.TransactionsStateRequest}
 */
proto.spacemesh.v1.TransactionsStateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.spacemesh.v1.TransactionsStateRequest;
  return proto.spacemesh.v1.TransactionsStateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.spacemesh.v1.TransactionsStateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.spacemesh.v1.TransactionsStateRequest}
 */
proto.spacemesh.v1.TransactionsStateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new types_pb.TransactionId;
      reader.readMessage(value,types_pb.TransactionId.deserializeBinaryFromReader);
      msg.addTransactionId(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeTransactions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.spacemesh.v1.TransactionsStateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.spacemesh.v1.TransactionsStateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.spacemesh.v1.TransactionsStateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spacemesh.v1.TransactionsStateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransactionIdList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      types_pb.TransactionId.serializeBinaryToWriter
    );
  }
  f = message.getIncludeTransactions();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * repeated TransactionId transaction_id = 1;
 * @return {!Array<!proto.spacemesh.v1.TransactionId>}
 */
proto.spacemesh.v1.TransactionsStateRequest.prototype.getTransactionIdList = function() {
  return /** @type{!Array<!proto.spacemesh.v1.TransactionId>} */ (
    jspb.Message.getRepeatedWrapperField(this, types_pb.TransactionId, 1));
};


/** @param {!Array<!proto.spacemesh.v1.TransactionId>} value */
proto.spacemesh.v1.TransactionsStateRequest.prototype.setTransactionIdList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.spacemesh.v1.TransactionId=} opt_value
 * @param {number=} opt_index
 * @return {!proto.spacemesh.v1.TransactionId}
 */
proto.spacemesh.v1.TransactionsStateRequest.prototype.addTransactionId = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.spacemesh.v1.TransactionId, opt_index);
};


proto.spacemesh.v1.TransactionsStateRequest.prototype.clearTransactionIdList = function() {
  this.setTransactionIdList([]);
};


/**
 * optional bool include_transactions = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.spacemesh.v1.TransactionsStateRequest.prototype.getIncludeTransactions = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.spacemesh.v1.TransactionsStateRequest.prototype.setIncludeTransactions = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.spacemesh.v1.TransactionsStateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.spacemesh.v1.TransactionsStateResponse.repeatedFields_, null);
};
goog.inherits(proto.spacemesh.v1.TransactionsStateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.spacemesh.v1.TransactionsStateResponse.displayName = 'proto.spacemesh.v1.TransactionsStateResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.spacemesh.v1.TransactionsStateResponse.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.spacemesh.v1.TransactionsStateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.spacemesh.v1.TransactionsStateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.spacemesh.v1.TransactionsStateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spacemesh.v1.TransactionsStateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    transactionsStateList: jspb.Message.toObjectList(msg.getTransactionsStateList(),
    proto.spacemesh.v1.TransactionState.toObject, includeInstance),
    transactionsList: jspb.Message.toObjectList(msg.getTransactionsList(),
    types_pb.Transaction.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.spacemesh.v1.TransactionsStateResponse}
 */
proto.spacemesh.v1.TransactionsStateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.spacemesh.v1.TransactionsStateResponse;
  return proto.spacemesh.v1.TransactionsStateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.spacemesh.v1.TransactionsStateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.spacemesh.v1.TransactionsStateResponse}
 */
proto.spacemesh.v1.TransactionsStateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.spacemesh.v1.TransactionState;
      reader.readMessage(value,proto.spacemesh.v1.TransactionState.deserializeBinaryFromReader);
      msg.addTransactionsState(value);
      break;
    case 2:
      var value = new types_pb.Transaction;
      reader.readMessage(value,types_pb.Transaction.deserializeBinaryFromReader);
      msg.addTransactions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.spacemesh.v1.TransactionsStateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.spacemesh.v1.TransactionsStateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.spacemesh.v1.TransactionsStateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spacemesh.v1.TransactionsStateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransactionsStateList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.spacemesh.v1.TransactionState.serializeBinaryToWriter
    );
  }
  f = message.getTransactionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      types_pb.Transaction.serializeBinaryToWriter
    );
  }
};


/**
 * repeated TransactionState transactions_state = 1;
 * @return {!Array<!proto.spacemesh.v1.TransactionState>}
 */
proto.spacemesh.v1.TransactionsStateResponse.prototype.getTransactionsStateList = function() {
  return /** @type{!Array<!proto.spacemesh.v1.TransactionState>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.spacemesh.v1.TransactionState, 1));
};


/** @param {!Array<!proto.spacemesh.v1.TransactionState>} value */
proto.spacemesh.v1.TransactionsStateResponse.prototype.setTransactionsStateList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.spacemesh.v1.TransactionState=} opt_value
 * @param {number=} opt_index
 * @return {!proto.spacemesh.v1.TransactionState}
 */
proto.spacemesh.v1.TransactionsStateResponse.prototype.addTransactionsState = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.spacemesh.v1.TransactionState, opt_index);
};


proto.spacemesh.v1.TransactionsStateResponse.prototype.clearTransactionsStateList = function() {
  this.setTransactionsStateList([]);
};


/**
 * repeated Transaction transactions = 2;
 * @return {!Array<!proto.spacemesh.v1.Transaction>}
 */
proto.spacemesh.v1.TransactionsStateResponse.prototype.getTransactionsList = function() {
  return /** @type{!Array<!proto.spacemesh.v1.Transaction>} */ (
    jspb.Message.getRepeatedWrapperField(this, types_pb.Transaction, 2));
};


/** @param {!Array<!proto.spacemesh.v1.Transaction>} value */
proto.spacemesh.v1.TransactionsStateResponse.prototype.setTransactionsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.spacemesh.v1.Transaction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.spacemesh.v1.Transaction}
 */
proto.spacemesh.v1.TransactionsStateResponse.prototype.addTransactions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.spacemesh.v1.Transaction, opt_index);
};


proto.spacemesh.v1.TransactionsStateResponse.prototype.clearTransactionsList = function() {
  this.setTransactionsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.spacemesh.v1.TransactionsStateStreamRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.spacemesh.v1.TransactionsStateStreamRequest.repeatedFields_, null);
};
goog.inherits(proto.spacemesh.v1.TransactionsStateStreamRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.spacemesh.v1.TransactionsStateStreamRequest.displayName = 'proto.spacemesh.v1.TransactionsStateStreamRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.spacemesh.v1.TransactionsStateStreamRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.spacemesh.v1.TransactionsStateStreamRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.spacemesh.v1.TransactionsStateStreamRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.spacemesh.v1.TransactionsStateStreamRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spacemesh.v1.TransactionsStateStreamRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    transactionIdList: jspb.Message.toObjectList(msg.getTransactionIdList(),
    types_pb.TransactionId.toObject, includeInstance),
    includeTransactions: jspb.Message.getFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.spacemesh.v1.TransactionsStateStreamRequest}
 */
proto.spacemesh.v1.TransactionsStateStreamRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.spacemesh.v1.TransactionsStateStreamRequest;
  return proto.spacemesh.v1.TransactionsStateStreamRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.spacemesh.v1.TransactionsStateStreamRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.spacemesh.v1.TransactionsStateStreamRequest}
 */
proto.spacemesh.v1.TransactionsStateStreamRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new types_pb.TransactionId;
      reader.readMessage(value,types_pb.TransactionId.deserializeBinaryFromReader);
      msg.addTransactionId(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeTransactions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.spacemesh.v1.TransactionsStateStreamRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.spacemesh.v1.TransactionsStateStreamRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.spacemesh.v1.TransactionsStateStreamRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spacemesh.v1.TransactionsStateStreamRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransactionIdList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      types_pb.TransactionId.serializeBinaryToWriter
    );
  }
  f = message.getIncludeTransactions();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * repeated TransactionId transaction_id = 1;
 * @return {!Array<!proto.spacemesh.v1.TransactionId>}
 */
proto.spacemesh.v1.TransactionsStateStreamRequest.prototype.getTransactionIdList = function() {
  return /** @type{!Array<!proto.spacemesh.v1.TransactionId>} */ (
    jspb.Message.getRepeatedWrapperField(this, types_pb.TransactionId, 1));
};


/** @param {!Array<!proto.spacemesh.v1.TransactionId>} value */
proto.spacemesh.v1.TransactionsStateStreamRequest.prototype.setTransactionIdList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.spacemesh.v1.TransactionId=} opt_value
 * @param {number=} opt_index
 * @return {!proto.spacemesh.v1.TransactionId}
 */
proto.spacemesh.v1.TransactionsStateStreamRequest.prototype.addTransactionId = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.spacemesh.v1.TransactionId, opt_index);
};


proto.spacemesh.v1.TransactionsStateStreamRequest.prototype.clearTransactionIdList = function() {
  this.setTransactionIdList([]);
};


/**
 * optional bool include_transactions = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.spacemesh.v1.TransactionsStateStreamRequest.prototype.getIncludeTransactions = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.spacemesh.v1.TransactionsStateStreamRequest.prototype.setIncludeTransactions = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.spacemesh.v1.TransactionsStateStreamResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.spacemesh.v1.TransactionsStateStreamResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.spacemesh.v1.TransactionsStateStreamResponse.displayName = 'proto.spacemesh.v1.TransactionsStateStreamResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.spacemesh.v1.TransactionsStateStreamResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.spacemesh.v1.TransactionsStateStreamResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.spacemesh.v1.TransactionsStateStreamResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spacemesh.v1.TransactionsStateStreamResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    transactionState: (f = msg.getTransactionState()) && proto.spacemesh.v1.TransactionState.toObject(includeInstance, f),
    transaction: (f = msg.getTransaction()) && types_pb.Transaction.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.spacemesh.v1.TransactionsStateStreamResponse}
 */
proto.spacemesh.v1.TransactionsStateStreamResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.spacemesh.v1.TransactionsStateStreamResponse;
  return proto.spacemesh.v1.TransactionsStateStreamResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.spacemesh.v1.TransactionsStateStreamResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.spacemesh.v1.TransactionsStateStreamResponse}
 */
proto.spacemesh.v1.TransactionsStateStreamResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.spacemesh.v1.TransactionState;
      reader.readMessage(value,proto.spacemesh.v1.TransactionState.deserializeBinaryFromReader);
      msg.setTransactionState(value);
      break;
    case 2:
      var value = new types_pb.Transaction;
      reader.readMessage(value,types_pb.Transaction.deserializeBinaryFromReader);
      msg.setTransaction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.spacemesh.v1.TransactionsStateStreamResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.spacemesh.v1.TransactionsStateStreamResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.spacemesh.v1.TransactionsStateStreamResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spacemesh.v1.TransactionsStateStreamResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransactionState();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.spacemesh.v1.TransactionState.serializeBinaryToWriter
    );
  }
  f = message.getTransaction();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      types_pb.Transaction.serializeBinaryToWriter
    );
  }
};


/**
 * optional TransactionState transaction_state = 1;
 * @return {?proto.spacemesh.v1.TransactionState}
 */
proto.spacemesh.v1.TransactionsStateStreamResponse.prototype.getTransactionState = function() {
  return /** @type{?proto.spacemesh.v1.TransactionState} */ (
    jspb.Message.getWrapperField(this, proto.spacemesh.v1.TransactionState, 1));
};


/** @param {?proto.spacemesh.v1.TransactionState|undefined} value */
proto.spacemesh.v1.TransactionsStateStreamResponse.prototype.setTransactionState = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.spacemesh.v1.TransactionsStateStreamResponse.prototype.clearTransactionState = function() {
  this.setTransactionState(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.spacemesh.v1.TransactionsStateStreamResponse.prototype.hasTransactionState = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Transaction transaction = 2;
 * @return {?proto.spacemesh.v1.Transaction}
 */
proto.spacemesh.v1.TransactionsStateStreamResponse.prototype.getTransaction = function() {
  return /** @type{?proto.spacemesh.v1.Transaction} */ (
    jspb.Message.getWrapperField(this, types_pb.Transaction, 2));
};


/** @param {?proto.spacemesh.v1.Transaction|undefined} value */
proto.spacemesh.v1.TransactionsStateStreamResponse.prototype.setTransaction = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.spacemesh.v1.TransactionsStateStreamResponse.prototype.clearTransaction = function() {
  this.setTransaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.spacemesh.v1.TransactionsStateStreamResponse.prototype.hasTransaction = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.spacemesh.v1.TransactionState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.spacemesh.v1.TransactionState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.spacemesh.v1.TransactionState.displayName = 'proto.spacemesh.v1.TransactionState';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.spacemesh.v1.TransactionState.prototype.toObject = function(opt_includeInstance) {
  return proto.spacemesh.v1.TransactionState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.spacemesh.v1.TransactionState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spacemesh.v1.TransactionState.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && types_pb.TransactionId.toObject(includeInstance, f),
    state: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.spacemesh.v1.TransactionState}
 */
proto.spacemesh.v1.TransactionState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.spacemesh.v1.TransactionState;
  return proto.spacemesh.v1.TransactionState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.spacemesh.v1.TransactionState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.spacemesh.v1.TransactionState}
 */
proto.spacemesh.v1.TransactionState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new types_pb.TransactionId;
      reader.readMessage(value,types_pb.TransactionId.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {!proto.spacemesh.v1.TransactionState.TransactionState} */ (reader.readEnum());
      msg.setState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.spacemesh.v1.TransactionState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.spacemesh.v1.TransactionState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.spacemesh.v1.TransactionState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.spacemesh.v1.TransactionState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      types_pb.TransactionId.serializeBinaryToWriter
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.spacemesh.v1.TransactionState.TransactionState = {
  TRANSACTION_STATE_UNSPECIFIED: 0,
  TRANSACTION_STATE_REJECTED: 1,
  TRANSACTION_STATE_INSUFFICIENT_FUNDS: 2,
  TRANSACTION_STATE_CONFLICTING: 3,
  TRANSACTION_STATE_MEMPOOL: 4,
  TRANSACTION_STATE_MESH: 5,
  TRANSACTION_STATE_PROCESSED: 6
};

/**
 * optional TransactionId id = 1;
 * @return {?proto.spacemesh.v1.TransactionId}
 */
proto.spacemesh.v1.TransactionState.prototype.getId = function() {
  return /** @type{?proto.spacemesh.v1.TransactionId} */ (
    jspb.Message.getWrapperField(this, types_pb.TransactionId, 1));
};


/** @param {?proto.spacemesh.v1.TransactionId|undefined} value */
proto.spacemesh.v1.TransactionState.prototype.setId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.spacemesh.v1.TransactionState.prototype.clearId = function() {
  this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.spacemesh.v1.TransactionState.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TransactionState state = 2;
 * @return {!proto.spacemesh.v1.TransactionState.TransactionState}
 */
proto.spacemesh.v1.TransactionState.prototype.getState = function() {
  return /** @type {!proto.spacemesh.v1.TransactionState.TransactionState} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.spacemesh.v1.TransactionState.TransactionState} value */
proto.spacemesh.v1.TransactionState.prototype.setState = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


goog.object.extend(exports, proto.spacemesh.v1);
