const ipcConsts = {
  SAVE_FILE: 'SAVE_FILE',
  SAVE_FILE_SUCCESS: 'SAVE_FILE_SUCCESS',
  SAVE_FILE_FAILURE: 'SAVE_FILE_FAILURE',
  READ_FILE: 'READ_FILE',
  READ_FILE_SUCCESS: 'READ_FILE_SUCCESS',
  READ_FILE_FAILURE: 'READ_FILE_FAILURE',
  SEND_REQUEST: 'SEND_REQUEST',
  REQUEST_RESPONSE_SUCCESS: 'REQUEST_RESPONSE_SUCCESS',
  REQUEST_RESPONSE_FAILURE: 'REQUEST_RESPONSE_FAILURE'
};

export default ipcConsts;
