enum IpcChannel {
  PRINT = 'PRINT',
  RELOAD_APP = 'RELOAD_APP',
  CLOSING_APP = 'CLOSING_APP',
  TOGGLE_AUTO_START = 'TOGGLE_AUTO_START',
  IS_AUTO_START_ENABLED_REQUEST = 'IS_AUTO_START_ENABLED_REQUEST',
  SET_NODE_PORT = 'SET_NODE_PORT',
  // Theme
  GET_OS_THEME_COLOR = 'GET_OS_THEME_COLOR',
  OPEN_BROWSER_VIEW = 'OPEN_BROWSER_VIEW',
  DESTROY_BROWSER_VIEW = 'DESTROY_BROWSER_VIEW',
  SEND_THEME_COLOR = 'SEND_THEME_COLOR',

  // Networks
  LIST_NETWORKS = 'LIST_NETWORKS',
  SWITCH_NETWORK = 'SWITCH_NETWORK',
  REQUEST_SWITCH_NETWORK = 'REQUEST_SWITCH_NETWORK',
  // Public services
  LIST_PUBLIC_SERVICES = 'LIST_PUBLIC_SERVICES',
  // Switching modes (Wallet / Local node)
  SWITCH_API_PROVIDER = 'SWITCH_API_PROVIDER',
  /** *********************************************************************** API 2.0 ********************************************************** */
  // Smesher Service calls
  SMESHER_SET_SETTINGS_AND_STARTUP_STATUS = 'SMESHER_SET_SETTINGS_AND_STARTUP_STATUS',
  SMESHER_SEND_SMESHING_CONFIG = 'SMESHER_SEND_SMESHING_CONFIG',
  SMESHER_SELECT_POST_FOLDER = 'SMESHER_SELECT_POST_FOLDER',
  SMESHER_CHECK_FREE_SPACE = 'SMESHER_CHECK_FREE_SPACE',
  SMESHER_START_SMESHING = 'SMESHER_START_SMESHING',
  SMESHER_STOP_SMESHING = 'SMESHER_STOP_SMESHING',
  SMESHER_GET_COINBASE = 'SMESHER_GET_COINBASE',
  SMESHER_SET_COINBASE = 'SMESHER_SET_COINBASE',
  SMESHER_GET_MIN_GAS = 'SMESHER_GET_MIN_GAS',
  SMESHER_GET_ESTIMATED_REWARDS = 'SMESHER_GET_ESTIMATED_REWARDS',
  SMESHER_SET_SETUP_COMPUTE_PROVIDERS = 'SMESHER_SET_SETUP_COMPUTE_PROVIDERS',
  SMESHER_POST_DATA_CREATION_PROGRESS = 'SMESHER_POST_DATA_CREATION_PROGRESS',
  // Wallet Manager
  W_M_GET_NETWORK_DEFINITIONS = 'W_M_GET_NETWORK_DEFINITIONS',
  W_M_GET_GLOBAL_STATE_HASH = 'W_M_GET_GLOBAL_STATE_HASH',
  W_M_GET_CURRENT_LAYER = 'W_M_GET_CURRENT_LAYER',
  W_M_CREATE_WALLET = 'W_M_CREATE_WALLET',
  W_M_UNLOCK_WALLET = 'W_M_UNLOCK_WALLET',
  W_M_COPY_FILE = 'W_M_COPY_FILE',
  W_M_UPDATE_WALLET_META = 'W_M_UPDATE_WALLET_META',
  W_M_UPDATE_WALLET_SECRETS = 'W_M_UPDATE_WALLET_SECRETS',
  W_M_CREATE_NEW_ACCOUNT = 'W_M_CREATE_NEW_ACCOUNT',
  READ_WALLET_FILES = 'READ_WALLET_FILES',
  W_M_SHOW_FILE_IN_FOLDER = 'W_M_SHOW_FILE_IN_FOLDER',
  W_M_SHOW_DELETE_FILE = 'W_M_SHOW_DELETE_FILE',
  W_M_WIPE_OUT = 'W_M_WIPE_OUT',
  W_M_SIGN_MESSAGE = 'W_M_SIGN_MESSAGE',
  W_M_GET_GET_ACCOUNT_REWARDS = 'W_M_GET_GET_ACCOUNT_REWARDS',
  W_M_SEND_TX = 'W_M_SEND_TX',
  W_M_UPDATE_TX_NOTE = 'W_M_UPDATE_TX_NOTE',
  // Transactions Manager
  T_M_UPDATE_ACCOUNT = 'T_M_UPDATE_ACCOUNT',
  T_M_UPDATE_TXS = 'T_M_UPDATE_TXS',
  T_M_UPDATE_REWARDS = 'T_M_UPDATE_REWARDS',
  // Node Manager
  N_M_GET_VERSION_AND_BUILD = 'N_M_GET_VERSION_AND_BUILD',
  N_M_SET_NODE_STATUS = 'N_M_SET_NODE_STATUS',
  N_M_SET_NODE_ERROR = 'N_M_SET_NODE_ERROR',
  N_M_RESTART_NODE = 'N_M_RESTART_NODE',
  N_M_START_NODE = 'N_M_START_NODE',
  N_M_STOP_NODE = 'N_M_STOP_NODE',
}

export default IpcChannel;
