const ipcConsts = {
  CREATE_WALLET_FILE: 'CREATE_WALLET_FILE',
  UNLOCK_WALLET_FILE: 'UNLOCK_WALLET_FILE',
  COPY_FILE: 'COPY_FILE',
  UPDATE_WALLET_FILE: 'UPDATE_WALLET_FILE',
  CREATE_NEW_ACCOUNT: 'CREATE_NEW_ACCOUNT',
  READ_WALLET_FILES: 'READ_WALLET_FILES',
  PRINT: 'PRINT',
  GET_AUDIO_PATH_RESPONSE: 'GET_AUDIO_PATH_RESPONSE',
  SHOW_FILE_IN_FOLDER: 'SHOW_FILE_IN_FOLDER',
  GET_NODE_SETTINGS: 'GET_NODE_SETTINGS',
  SET_NODE_IP: 'SET_NODE_IP',
  RELOAD_APP: 'RELOAD_APP',
  DELETE_FILE: 'DELETE_FILE',
  WIPE_OUT: 'WIPE_OUT',
  TOGGLE_AUTO_START: 'TOGGLE_AUTO_START',
  IS_AUTO_START_ENABLED_REQUEST: 'IS_AUTO_START_ENABLED_REQUEST',
  CLOSING_APP: 'CLOSING_APP',
  START_NODE: 'START_NODE',
  SET_NODE_PORT: 'SET_NODE_PORT',
  SIGN_MESSAGE: 'SIGN_MESSAGE',
  IS_SERVICE_READY: 'IS_SERVICE_READY',
  // gRPC calls
  // Node management
  GET_NODE_STATUS: 'GET_NODE_STATUS',
  GET_ACCOUNT_REWARDS: 'GET_ACCOUNT_REWARDS',
  // Wallet management
  GET_BALANCE: 'GET_BALANCE',
  SEND_TX: 'SEND_TX',
  UPDATE_TX: 'UPDATE_TX',
  GET_ACCOUNT_TXS: 'GET_ACCOUNT_TXS',
  // Theme
  GET_OS_THEME_COLOR: 'GET_OS_THEME_COLOR',
  OPEN_BROWSER_VIEW: 'OPEN_BROWSER_VIEW',
  DESTROY_BROWSER_VIEW: 'DESTROY_BROWSER_VIEW',
  SEND_THEME_COLOR: 'SEND_THEME_COLOR',

  // Other
  OPEN_EXTERNAL_LINK: 'OPEN_EXTERNAL_LINK',
  /** *********************************************************************** API 2.0 ********************************************************** */
  // Services activation calls
  START_SMESHER_SERVICE: 'START_SMESHER_SERVICE',
  // Smesher Service calls
  SMESHER_GET_SETTINGS: 'SMESHER_GET_SETTINGS',
  SMESHER_SELECT_POST_FOLDER: 'SMESHER_SELECT_POST_FOLDER',
  SMESHER_CHECK_FREE_SPACE: 'SMESHER_CHECK_FREE_SPACE',
  SMESHER_IS_SMESHING: 'SMESHER_IS_SMESHING',
  SMESHER_START_SMESHING: 'SMESHER_START_SMESHING',
  SMESHER_STOP_SMESHING: 'SMESHER_STOP_SMESHING',
  SMESHER_GET_SMESHER_ID: 'SMESHER_GET_SMESHER_ID',
  SMESHER_GET_COINBASE: 'SMESHER_GET_COINBASE',
  SMESHER_SET_COINBASE: 'SMESHER_SET_COINBASE',
  SMESHER_GET_MIN_GAS: 'SMESHER_GET_MIN_GAS',
  SMESHER_GET_ESTIMATED_REWARDS: 'SMESHER_GET_ESTIMATED_REWARDS',
  SMESHER_GET_POST_STATUS: 'SMESHER_GET_POST_STATUS',
  SMESHER_GET_POST_COMPUTE_PROVIDERS: 'SMESHER_GET_POST_COMPUTE_PROVIDERS',
  SMESHER_CREATE_POST_DATA: 'SMESHER_CREATE_POST_DATA',
  SMESHER_STOP_POST_DATA_CREATION: 'SMESHER_STOP_POST_DATA_CREATION',
  SMESHER_POST_DATA_CREATION_PROGRESS: 'SMESHER_POST_DATA_CREATION_PROGRESS'
};

export default ipcConsts;
