const ipcConsts = {
  // node fs calls
  SAVE_FILE: 'SAVE_FILE',
  SAVE_FILE_SUCCESS: 'SAVE_FILE_SUCCESS',
  SAVE_FILE_FAILURE: 'SAVE_FILE_FAILURE',
  READ_FILE: 'READ_FILE',
  READ_FILE_SUCCESS: 'READ_FILE_SUCCESS',
  READ_FILE_FAILURE: 'READ_FILE_FAILURE',
  GET_FILE_NAME: 'GET_FILE_NAME',
  GET_FILE_NAME_SUCCESS: 'GET_FILE_NAME_SUCCESS',
  GET_FILE_NAME_FAILURE: 'GET_FILE_NAME_FAILURE',
  READ_DIRECTORY: 'READ_DIRECTORY',
  READ_DIRECTORY_SUCCESS: 'READ_DIRECTORY_SUCCESS',
  READ_DIRECTORY_FAILURE: 'READ_DIRECTORY_FAILURE',
  UPDATE_FILE: 'UPDATE_FILE',
  UPDATE_FILE_SUCCESS: 'UPDATE_FILE_SUCCESS',
  UPDATE_FILE_FAILURE: 'UPDATE_FILE_FAILURE',
  GET_DRIVE_LIST: 'GET_DRIVE_LIST',
  GET_DRIVE_LIST_SUCCESS: 'GET_DRIVE_LIST_SUCCESS',
  GET_DRIVE_LIST_FAILURE: 'GET_DRIVE_LIST_FAILURE',
  GET_AVAILABLE_DISK_SPACE: 'GET_AVAILABLE_DISK_SPACE',
  GET_AVAILABLE_DISK_SPACE_SUCCESS: 'GET_AVAILABLE_DISK_SPACE_SUCCESS',
  GET_AVAILABLE_DISK_SPACE_FAILURE: 'GET_AVAILABLE_DISK_SPACE_FAILURE',
  PRINT: 'PRINT',
  // gRPC calls
  GET_BALANCE: 'GET_BALANCE',
  GET_BALANCE_SUCCESS: 'GET_BALANCE_SUCCESS',
  GET_BALANCE_FAILURE: 'GET_BALANCE_FAILURE',
  SEND_TX: 'SEND_TX',
  SEND_TX_SUCCESS: 'SEND_TX_SUCCESS',
  SEND_TX_FAILURE: 'SEND_TX_FAILURE'
};

export default ipcConsts;
