name: Lint And App Build

on:
  push:
    branches-ignore:
      - 'master'
    tags-ignore:
      - v0.*
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: npm install
        run: |
          npm install
      - name: npm lint and build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run lint-ci
          npm run build-dll
      - if: matrix.os == 'macos-latest'
        name: download macos node binary
        run: |
          curl --output ./node/mac/go-spacemesh --create-dirs https://github.com/spacemeshos/go-spacemesh/releases/download/v0.1.15-a/go-spacemesh-osx
          npm run package-mac
        env:
          CSC_LINK: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          CSC_KEY_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
          APPLEID: ${{ secrets.APPLE_ID }}
          APPLEIDPASS: ${{ secrets.APPLE_ID_PASS }}
